# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\show_orders.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 540)
        Form.setMinimumSize(QtCore.QSize(1250, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget228 = QtWidgets.QTableWidget(Form)
        self.tableWidget228.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget228.setObjectName("tableWidget228")
        self.tableWidget228.setColumnCount(6)
        self.tableWidget228.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget228.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget228.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget228.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget228.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget228.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget228.setHorizontalHeaderItem(5, item)
        self.tableWidget228.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget228.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget228.horizontalHeader().setStretchLastSection(True)
        self.tableWidget228.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget228)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget228.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название сайта"))
        item = self.tableWidget228.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Описание"))
        item = self.tableWidget228.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Вид сайта"))
        item = self.tableWidget228.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Есть ли дизайн"))
        item = self.tableWidget228.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Цена"))
        item = self.tableWidget228.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Срок до"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
